config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  root "pages#landing"
  get "pages/about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing;
  end
  def about;
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html lang="en">
      <head>
        <title>Myapp</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <%= javascript_importmap_tags %>
      </head>

      <body>
          <div class="container-fluid container-background">
            <div class="container">

              <ul class="nav nav-pills nav-justified">
                <li class="nav-item">
                  <%= link_to "Главнвя", root_path, class: 'nav-link active' %>
                </li>
                <li class="nav-item">
                  <%= link_to "О нас", pages_about_path, class: 'nav-link active' %>
                </li>
          <% if user_signed_in? %>
                      <li class="nav-item">
                      <%= link_to "выйти", destroy_user_session_path, class: 'nav-link active' %>
                    </li><% end %>
              </ul>

              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>

              <%= yield %>
            </div>
          </div>
      </body>
  </html>

app/views/pages/about.html.erb
<h1>О нас</h1>
<p>приложение</p>

app/views/pages/landing.html.erb
<% if user_signed_in? %>

  <% else %>
        <div class="card background-color card-landing">
              <div class="card-body">
                <h4 class="card-title card-cap-bg">Присоединяйся</h4>
              </div>
                <div class="card-header">
                  <h5 class="card-title">Делитесь своими имоциями</h5>
                  <p class="card-text">Размещайте свои фотографии и подписывайтесь друг на друга.</p>
                  <%= link_to "Создать аккаунт", new_user_registration_path, class: "btn btn-success" %>
                  <%= link_to "Войти", new_user_session_path, class: "btn btn-success" %>
                </div>
        </div>
<% end %>